/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RoomsSlugRouteImport } from './routes/rooms.$slug'
import { Route as BlogThingsToDoSriGanganagarRouteImport } from './routes/blog.things-to-do-sri-ganganagar'
import { Route as BlogHeritageAndAmenitiesRouteImport } from './routes/blog.heritage-and-amenities'
import { Route as BlogBestTimeToVisitRouteImport } from './routes/blog.best-time-to-visit'
import { Route as ApiBookRouteImport } from './routes/api/book'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsSlugRoute = RoomsSlugRouteImport.update({
  id: '/rooms/$slug',
  path: '/rooms/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogThingsToDoSriGanganagarRoute =
  BlogThingsToDoSriGanganagarRouteImport.update({
    id: '/blog/things-to-do-sri-ganganagar',
    path: '/blog/things-to-do-sri-ganganagar',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogHeritageAndAmenitiesRoute =
  BlogHeritageAndAmenitiesRouteImport.update({
    id: '/blog/heritage-and-amenities',
    path: '/blog/heritage-and-amenities',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogBestTimeToVisitRoute = BlogBestTimeToVisitRouteImport.update({
  id: '/blog/best-time-to-visit',
  path: '/blog/best-time-to-visit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBookRoute = ApiBookRouteImport.update({
  id: '/api/book',
  path: '/api/book',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/book': typeof ApiBookRoute
  '/blog/best-time-to-visit': typeof BlogBestTimeToVisitRoute
  '/blog/heritage-and-amenities': typeof BlogHeritageAndAmenitiesRoute
  '/blog/things-to-do-sri-ganganagar': typeof BlogThingsToDoSriGanganagarRoute
  '/rooms/$slug': typeof RoomsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/book': typeof ApiBookRoute
  '/blog/best-time-to-visit': typeof BlogBestTimeToVisitRoute
  '/blog/heritage-and-amenities': typeof BlogHeritageAndAmenitiesRoute
  '/blog/things-to-do-sri-ganganagar': typeof BlogThingsToDoSriGanganagarRoute
  '/rooms/$slug': typeof RoomsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/book': typeof ApiBookRoute
  '/blog/best-time-to-visit': typeof BlogBestTimeToVisitRoute
  '/blog/heritage-and-amenities': typeof BlogHeritageAndAmenitiesRoute
  '/blog/things-to-do-sri-ganganagar': typeof BlogThingsToDoSriGanganagarRoute
  '/rooms/$slug': typeof RoomsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/sitemap.xml'
    | '/api/book'
    | '/blog/best-time-to-visit'
    | '/blog/heritage-and-amenities'
    | '/blog/things-to-do-sri-ganganagar'
    | '/rooms/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/sitemap.xml'
    | '/api/book'
    | '/blog/best-time-to-visit'
    | '/blog/heritage-and-amenities'
    | '/blog/things-to-do-sri-ganganagar'
    | '/rooms/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/sitemap.xml'
    | '/api/book'
    | '/blog/best-time-to-visit'
    | '/blog/heritage-and-amenities'
    | '/blog/things-to-do-sri-ganganagar'
    | '/rooms/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiBookRoute: typeof ApiBookRoute
  BlogBestTimeToVisitRoute: typeof BlogBestTimeToVisitRoute
  BlogHeritageAndAmenitiesRoute: typeof BlogHeritageAndAmenitiesRoute
  BlogThingsToDoSriGanganagarRoute: typeof BlogThingsToDoSriGanganagarRoute
  RoomsSlugRoute: typeof RoomsSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms/$slug': {
      id: '/rooms/$slug'
      path: '/rooms/$slug'
      fullPath: '/rooms/$slug'
      preLoaderRoute: typeof RoomsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/things-to-do-sri-ganganagar': {
      id: '/blog/things-to-do-sri-ganganagar'
      path: '/blog/things-to-do-sri-ganganagar'
      fullPath: '/blog/things-to-do-sri-ganganagar'
      preLoaderRoute: typeof BlogThingsToDoSriGanganagarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/heritage-and-amenities': {
      id: '/blog/heritage-and-amenities'
      path: '/blog/heritage-and-amenities'
      fullPath: '/blog/heritage-and-amenities'
      preLoaderRoute: typeof BlogHeritageAndAmenitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/best-time-to-visit': {
      id: '/blog/best-time-to-visit'
      path: '/blog/best-time-to-visit'
      fullPath: '/blog/best-time-to-visit'
      preLoaderRoute: typeof BlogBestTimeToVisitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/book': {
      id: '/api/book'
      path: '/api/book'
      fullPath: '/api/book'
      preLoaderRoute: typeof ApiBookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiBookRoute: ApiBookRoute,
  BlogBestTimeToVisitRoute: BlogBestTimeToVisitRoute,
  BlogHeritageAndAmenitiesRoute: BlogHeritageAndAmenitiesRoute,
  BlogThingsToDoSriGanganagarRoute: BlogThingsToDoSriGanganagarRoute,
  RoomsSlugRoute: RoomsSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
